; PlatformIO Project Configuration File
; NodeMCU ESP8266 Forest Fire Detection System
;

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = +<**> -<.ino>

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4
